Support Naming Policy
cybozu-go/accurate pull request #17
Opened 2021-09-21 18:08 UTC by bells17

#6

2021-09-26 14:45 UTC, ymmt2005 requested changes
Please validate the regular expressions beforehand, as commented.
Also, please add a user manual for this feature.

2021-09-26 14:45 UTC, ymmt2005 commented on hooks/subnamespace.go
> +func (v *subNamespaceValidator) notMatchingNamingPolicy(ctx context.Context, sn *accuratev1.SubNamespace) (bool, error) {
The regular expression should be pre-compiled when loaded from the configuration file,
so that no error would be returned during execution.

2021-09-26 14:45 UTC, ymmt2005 commented on pkg/config/types.go
> +type NamingPolicy struct {
Add a comment for godoc.

2021-09-26 14:45 UTC, ymmt2005 commented on pkg/config/types.go
> +	Match string `json:"match,omitempty"`
These two are not expected to be empty, so `omitempty` should be removed.

2021-10-06 06:35 UTC, bells17 commented
Thank you @ymmt2005 .
I've corrected the points you commented on.
Would you review this PR again?

> Also, please add a user manual for this feature.

I added the description and example for the naming policy setting to values.yaml.
Should we write the docs aside from the above description and example?

2021-11-02 08:46 UTC, zoetrope submitted a review, later dismissed
LGTM

2021-11-02 08:54 UTC, ymmt2005 commented on pkg/config/types.go
> +// NamingPolicy represents the configuration of naming policies for Namespaces these are managed by Accurate.
```suggestion
// NamingPolicy represents naming policies for Namespaces created from SubNamespaces.
```

2021-11-05 06:15 UTC, zoetrope submitted a review, later dismissed
LGTM

2021-11-05 06:19 UTC, ymmt2005 commented
@bells17 
I'm  a little bit confused that there are almost two identical files, namely,
charts/accurate/values.yaml  and config.yaml.

Can we remove config.yaml?

2021-11-08 11:40 UTC, bells17 commented
@ymmt2005 Thank you for your reviewing and I removed config.yaml.
Would you check it?

2021-11-11 09:25 UTC, zoetrope approved these changes

2021-11-11 09:29 UTC, ymmt2005 approved these changes
LGTM

2021-11-11 09:30 UTC, merged